version: "3.8"
networks: 
  mongodb:
    external: true
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      PUID: 1000
      PGID: 1000
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb-data
    ports:
      - 27017:27017
    restart: unless-stopped